language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
  allow_failures:
    - nightly

install: composer update

script: bin/phpspec run --format=pretty
